name: "🧪 Physics task"
description: Physics implementation or validation work item
labels: ["physics"]
body:
  - type: input
    id: reference
    attributes:
      label: Reference
      description: Paper/PDG/experiment note to match
      placeholder: e.g., PDG 2024 §33, Geant4 EM Std
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What is being implemented or validated?
  - type: textarea
    id: datasets
    attributes:
      label: Datasets / configs
      description: Inputs, seeds, IOV tags
  - type: textarea
    id: metrics
    attributes:
      label: Metrics & bands
      description: What curves/plots and target bands?
      placeholder: |
        - Longitudinal <-> Geant4 within ±X%
        - Tracking eff vs pT within band
  - type: checkboxes
    id: deliverables
    attributes:
      label: Deliverables
      options:
        - label: Unit tests added
        - label: Validation plots saved under docs/validation
        - label: Notes in docs/physics-notes
        - label: Configs saved under configs/
