[build-system]
requires=['setuptools>=61.0']
build-backend='setuptools.build_meta'
[project]
name='pt-sim'
version='0.1.0'


[tool.ruff]
line-length = 100
target-version = "py311"
extend-select = ["E", "F"]