global_pt: {alpha_prime: 1.0, intercept: 1.0}
electron: {mass_mev: 0.511, charge: -1, spin: 0.5}
ecal_geom: {n: 32, cell_size_cm: 1.0, moliere_radius_cm: 2.0, depth_lambda: 25.0, sampling_fraction: 0.9, noise_sigma: 0.002}
shower: {a: 4.0, b: 0.30, lateral_sigma_cm: 1.2}
mode: accurate
material: {name: PbWO4, X0_cm: 0.89, RM_cm: 2.0, Ec_MeV: 9.0, sampling_fraction: 0.9, light_yield_pe_per_GeV: 20000.0, electronics_noise_GeV: 0.002}
