name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install package with test deps
        run: |
          python -m pip install --upgrade pip
          # Quote extras to avoid shell globbing: .[test] → '.[test]'
          pip install -e '.[test]'
          # Sanity checks so we fail early with a clear error
          python -c "import sys; print('Python:', sys.version)"
          python -c "import pkgutil; print('Has numpy?', pkgutil.find_loader('numpy') is not None)"
          # Fallback in case extras didn’t pull numpy (defensive only)
          pip show numpy || pip install numpy

      - name: Run mypy type checks
        run: |
          python -m mypy --ignore-missing-imports pt-sim/pt_sim

      - name: Run pytest
        run: |
          python -c "import numpy, sys; print('NumPy:', numpy.__version__, 'on', sys.version.split()[0])"
          pytest -q
